### ISSUE TITLE
Gantt chart rendering error

### ISSUE THREAD

**Issue by 00sapo** [rhysd/Shiba#47]
On my system (Linux) with Shiba downloaded from the release, I get a wrong mermaid rendering:
![image](https://user-images.githubusercontent.com/22996003/52713250-17f4d800-2f97-11e9-84a0-d69f72a105f5.png)

This is my `config.yml` (I tried various values of `drawer.responive`)
```yaml
drawer:
    responsive: false
markdown:
    css_path: '/opt/Shiba-linux-x64/tufte.css'
path_watcher.default_path: '/home/sapo/MEGAsync/SHARED/Notes/General.md'
```
